# Generated by Django 3.0.4 on 2020-03-30 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdown', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='lockdownEnd',
            field=models.DateField(),
        ),
    ]
