# Generated by Django 3.0.4 on 2020-03-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdown', '0002_auto_20200330_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='lockdownStart',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='lockdownEnd',
            field=models.DateField(auto_now=True),
        ),
    ]
