# Generated by Django 3.0.4 on 2020-03-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lockdown', '0004_auto_20200330_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='lockdownEnd',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='country',
            name='lockdownStart',
            field=models.DateTimeField(),
        ),
    ]
